version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TUNNEL=1
      - MODE=${MODE:-wasm}
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules


